### ISSUE TITLE
Änderungen an der "Live"-Seite

### ISSUE THREAD

**Issue by bluvel** [Anathema-e7/ZIMTOS-SPACEFIND-3000#16]
Änderungen im raumplan.html werden nicht in die Live-Seite übernommen.

**Comment by Anathema-e7** [comment]
Irgendwas stimmt hier echt nicht. Ich habe testweise das Wort "Test" in Lehrersuche.html reingeschrieben, die Änderung ist auch hier nicht zu sehen. Definitv ein Problem mit github, wenn wir das heute nicht zum laufen kriegen, werden wir wieder Dropbox für previews benutzen müssen. Nate kennt sich mit github mittlerweile besser aus.

Edit: Dropbox Link ist jetzt erstmal mit dabei.

**Comment by Anathema-e7** [comment]
So wie's aussieht, werden nur die Dateien im gh-pages Zweig angezeigt. Ich weiß nicht genau, wie ich den merge mit Konflikten pushe....

**Comment by Anathema-e7** [comment]
Nevermind, ich hab's hinbekommen. In Zukunft: Einfach gh-pages updaten, indem die Änderung der main Branch in die gh-pages Branch via pull request reingezogen werden.

**Comment by hylophile** [comment]
bzw gh-pages zu default branch machen. aber das is ja wohl schon passiert

**Comment by hylophile** [comment]
bzw

```
git checkout gh-pages
```
