### ISSUE TITLE
Ergänzung von lehrersuche.html mit Eingabekomponenten

### ISSUE THREAD

**Issue by Anathema-e7** [Anathema-e7/ZIMTOS-SPACEFIND-3000#2]
lehrersuche.html soll nach dem neuen [Konzept](https://www.dropbox.com/s/gzpan3k6dk2ew34/UI%20Vorschlag%205.png?dl=0) ergänzt werden. (fig. 3)
Nehme an, dass der Nutzer auf LPlan.html weitergeleitet wird, wenn der Suchvorgang gestartet wird.

**Comment by nokiki** [comment]
Formatierung kommt noch hinterher
Komponenten sind implementiert
