### ISSUE TITLE
lehrersuche is empty

### ISSUE THREAD

**Issue by hylophile** [Anathema-e7/ZIMTOS-SPACEFIND-3000#23]
i can't implement lehrersuche if there's no UI

**Comment by Anathema-e7** [comment]
Das ist seit einiger Zeit Lisa's Aufgabe. Ich schau noch, wie ich ihr helfen kann.

**Comment by nokiki** [comment]
dun.

**Comment by hylophile** [comment]
orly

**Comment by nokiki** [comment]
was fehlt noch

**Comment by nokiki** [comment]
vergessen zu syncen, änderungen sind jetzt da <.<
soz ._.

**Comment by hylophile** [comment]
nvm, gj :>

**Comment by nokiki** [comment]
ich weiß gehört hier nicht hin, aber nate wo müssen wir morgen hin? hab den namen vergessen :<
