### ISSUE TITLE
add settings at the top

### ISSUE THREAD

**Issue by hylophile** [Anathema-e7/ZIMTOS-SPACEFIND-3000#29]

**Comment by Anathema-e7** [comment]
Welche Settings und wo?

**Comment by hylophile** [comment]
schon gut, is halt den verbindung von den sprachen

**Comment by hylophile** [comment]
gucken sie bitte JETZT :>
jquery is toll.

**Comment by Anathema-e7** [comment]
Wie ich sehe, hast du eine Einstellungsseite reingesetzt. Nach dem neuen Konzept vom 08.12 wurde die aber rausgestrichen? https://www.dropbox.com/s/dtzzuqo5sw6ywat/UI%20Vorschlag%206.png?dl=0
Bastel an dem jQuery rum, wie du magst. Ich formatiere gerade die Seiten ein wenig um. Sollte doch noch eine Settings Seite anfallen, sag mir bescheid.

**Comment by hylophile** [comment]
naja ohne settings seite heisst das halt der user kann entweder nur ein einziges mal seine kurse eingeben, oder muss jedes mal auf anwenden klicken. und von wegen UX und so, is beides doof.

habs halt so gemacht dass man nur auf den stundenplan kommt wenn man settings eingegeben hat.

**Comment by hylophile** [comment]
also kursauswahl sind halt die settings. ich dachte das haetten wir so besprochen. wollt jetzt nicht auf teufel komm raus mein eigenes ding machen, aber ich denke die argumente sprechen fuer settings.

**Comment by Anathema-e7** [comment]
Kann dann wohl auch so bleiben. Dachte erst, das wäre momentan etwas redundant.
