### ISSUE TITLE
Einstellungsmöglichkeiten für den Stundenplan

### ISSUE THREAD

**Issue by Anathema-e7** [Anathema-e7/ZIMTOS-SPACEFIND-3000#3]
Die Einstellungsmöglichkeiten für den Stundenplan sind nach dem vom 08.12.2015 bestehendem [Konzept](https://www.dropbox.com/s/dtzzuqo5sw6ywat/UI%20Vorschlag%206.png?dl=0) zu implementieren.
- Es wird eine Seite SPlan erstellt.
- Diese Seite bekommt ein Dropdown Menü mit Tickboxes für jeden Kurs der Klasse OG3.
- EIn Knopf bestätigt die Auswahl.

**Comment by nokiki** [comment]
Formatierung kommt noch hinterher
Komponenten sind implementiert
