### ISSUE TITLE
settings werden nicht gespeichert

### ISSUE THREAD

**Issue by hylophile** [Anathema-e7/ZIMTOS-SPACEFIND-3000#30]
keine ahnung warum die funktionalitaet die ich eingebaut hab nicht mehr geht. schau ich mir morgen mal an.

**Comment by hylophile** [comment]
achso, klar. 1. die checkboxen lesen natuerlich noch nicht den speicher aus...

**Comment by Anathema-e7** [comment]
Komm mal Tox du Penner, ich kann dich nicht erreichen

**Comment by hylophile** [comment]
> samstag.

lehrersuche laeuft. heute noch die links anpassen, damit die settings nicht jedes mal neu abgefragt werden und der request beim stundenplan ggf nicht jedes mal neu gemacht wird

**Comment by hylophile** [comment]
wie waers mit nem update button beim stundenplan :>

**Comment by hylophile** [comment]
done
