### ISSUE TITLE
Gemeinsames Überprüfen des Designs

### ISSUE THREAD

**Issue by Anathema-e7** [Anathema-e7/ZIMTOS-SPACEFIND-3000#7]
Zum Ende der Fertigstellung der Seite sollte die Gruppe sich das Design anschauen und evtl. Verbesserungsvorschläge angeben.
Wichtig sind:
- Farbe
- Reihenfolge und Orientierung der Elemente
- Formulierung von Textstellen

**Comment by hylophile** [comment]
spielt vllt. keine rolle aber bei meinem browser wird dieses Teil rechts oben nicht angezeigt. Apropos, wie kann man das aufs handy packen?
